#pragma once

// THIS HEADER FILE IS AUTO GENERATED BY LUA SCRIPT, DO NOT TOUCH
// THIS IS A SIMPLE FACTORY PATTERN TO LOAD NEW SCENES AT RUNTIME

// once you have made a new scene, rebuild the solution on the command line
// the content of this file will be automatic updated to reflect the change

#include <iostream>
#include <string>
#include <vector>
#include "core/log.h"
#include "scene/scene.h"

#include "example/scene_01.h"
#include "example/scene_02.h"
#include "example/scene_03.h"

namespace scene::factory {

    inline const std::vector<std::string> titles {
        "Welcome Screen",
        "Demo Scene",
        "Environment Lighting (IBL)",
        "Disney BSDF"
    };

    inline Scene* LoadScene(const std::string& title) {
        if (title == "Welcome Screen") return new Scene(title);
        if (title == "Demo Scene") return new Scene01(title);
        if (title == "Environment Lighting (IBL)") return new Scene02(title);
        if (title == "Disney BSDF") return new Scene03(title);

        CORE_ERROR("Scene \"{0}\" is not registered in the factory ...", title);
        std::cin.get();
        exit(EXIT_FAILURE);
    }

}